"""add lab guide_url

Revision ID: 06e369fedb0f
Revises: 9c50deff5e28
Create Date: 2026-07-13 12:29:08.272730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e369fedb0f'
down_revision: Union[str, None] = '9c50deff5e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('guide_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labs', 'guide_url')
    # ### end Alembic commands ###
